module VariableMap
	# This module maps the database-specific variable names to friendly names
	#   and formatted values.
	# Variables without mapping should default to humanized names
	#   and the original, unformatted text.
  PRACTICE_MAP = {
    "id" => ["Database ID", nil],
    "name" => [nil, nil],
    "recruitment_source" => [nil, "Practice::RECRUITMENT_SOURCE_VALS"],
		"recruitment_source_referral" => [nil, nil],
    "prac_ehr_yr" => [nil, nil],
    "prac_ehrname" => [nil, "Practice::PRAC_EHRNAME_VALS"],
    "prac_ehrname_other" => [nil, nil],
    "prac_ehrversion" => [nil, nil],
    "prac_ehr_mu" => [nil, "Practice::YN12_VALS"],
		"prac_mu_stage1" => [nil, "Practice::PRAC_MU_STAGE1_VALS"],
		"prac_mu_stage2" => [nil, "Practice::YNMU1234_VALS"],
		"prac_ehr_extractdata" => [nil, "Practice::PRAC_EHR_EXTRACTDATA_VALS"],
		"prac_ehr_person_extractdata" => [nil, "Practice::PRAC_EHR_PERSON_EXTRACTDATA_VALS"],
		"prac_ehr_person_extractdata_other" => [nil, nil],
		"prac_it_support" => [nil, "Practice::PRAC_IT_SUPPORT_VALS"],
		"prac_ehr_vendor" => [nil, "Practice::PRAC_EHR_VENDOR_VALS"],
		"prac_share_healthinfo" => [nil, "Practice::YN12_VALS"],
		"prac_cqm" => [nil, nil],
		"prac_cqm_submit" => [nil, "Practice::PRAC_CQM_VALS"],
		"prac_cqm_who" => [nil, nil],
		"prac_ehr_satisfaction" => [nil, "Practice::SATISFIED1234_VALS"],
		"prac_new_ehr" => [nil, "Practice::YNMU1234_VALS"],
		"number_clinicians" => [nil, nil],
		"fte_clinicians" => [nil, nil],
		"prac_own_other_specify" => [nil, nil],
		"prac_own_yrs" => [nil, nil],
		"elig_clinic_count" => [nil, nil],
		"prac_spec_mix" => [nil, "Practice::PRAC_SPEC_MIX_VALS"],
		"prac_pcmh" => [nil, "Practice::YN12_VALS"],
		"primary_care" => [nil, "Practice::YN12_VALS"],
		"prac_ehr" => [nil, "Practice::PRAC_EHR_VALS"],
		"prac_ehr_mu_yr" => [nil, nil],
		"interest_yn" => [nil, "Practice::YN12_VALS"],
		"interest_why" => [nil, nil],
		"interest_why_not" => [nil, "Practice::INTEREST_WHY_NOT_VALS"],
		"interest_why_not_other" => [nil, nil],
		"interest_expect" => [nil, nil],
		"interest_challenge" => [nil, nil],
		"interest_contact_month" => [nil, "Practice::INTEREST_CONTACT_MONTH_VALS"],
		"current_partner" => [nil, nil],
		"parent_organization" => [nil, nil],
		"prac_state" => [nil, "Practice::PRAC_STATE_VALS"],
		"prac_own_clinician" => [nil, nil],
		"prac_own_hosp" => [nil, nil],
		"prac_own_hmo" => [nil, nil],
		"prac_own_fqhc" => [nil, nil],
		"prac_own_nonfed" => [nil, nil],
		"prac_own_academic" => [nil, nil],
		"prac_own_fed" => [nil, nil],
		"prac_own_rural" => [nil, nil],
		"prac_own_ihs" => [nil, nil],
		"prac_own_other" => [nil, nil],
		"prac_aco_medicaid" => [nil, nil],
		"prac_aco_medicare" => [nil, nil],
		"prac_aco_commercial" => [nil, nil],
		"prac_aco_other" => [nil, nil],
		"prac_aco_none" => [nil, nil],
		"prac_aco_dk" => [nil, nil],
		"prac_aco_join_medicaid" => [nil, "Practice::PRAC_ACO_JOIN_MEDICAID_VALS"],
		"prac_aco_join_medicare" => [nil, "Practice::PRAC_ACO_JOIN_MEDICARE_VALS"],
		"prac_aco_join_commercial" => [nil, "Practice::PRAC_ACO_JOIN_COMMERCIAL_VALS"],
		"zip_code" => [nil, nil],
		"city" => [nil, nil],
		"coach_id" => [nil, nil],
		"pc_name_cached" => [nil, nil],
		"la_date_cached" => [nil, nil],
		"pal_status_cached" => [nil, nil],
		"study_id" => [nil, nil],
		"residency_training_site" => [nil, nil],
		"site_id" => [nil, "Site::SITE_VALS"]
  }
end
